---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

Quality checks:
  extends: .quality_check

# Puppet 4.9.4 Unit Test:
#   extends: .unit_test
#   image: ruby:2.2.0
#   variables:
#     PUPPET_GEM_VERSION: '4.9.4'

# Puppet 4.10.12 Unit Test:
#   extends: .unit_test
#   image: ruby:2.2.0
#   variables:
#     PUPPET_GEM_VERSION: '4.10.12'

Puppet 5.0.1 Unit test:
  extends: .unit_test
  variables:
    PUPPET_GEM_VERSION: 5.0.1

Puppet 5.1.0 Unit test:
  extends: .unit_test
  variables:
    PUPPET_GEM_VERSION: 5.1.0

Puppet 5.2.0 Unit test:
  extends: .unit_test
  variables:
    PUPPET_GEM_VERSION: 5.2.0

Puppet 5.3.5 Unit test:
  extends: .unit_test
  variables:
    PUPPET_GEM_VERSION: 5.3.5

# Puppet 5.5.6 Unit test:
#   extends: .unit_test
#   variables:
#     PUPPET_GEM_VERSION: 5.5.6

# Puppet 6.0.7 Unit test:
#   extends: .unit_test
#   variables:
#     PUPPET_GEM_VERSION: 6.0.7

# Puppet 6.1.0 Unit test:
#   extends: .unit_test
#   variables:
#     PUPPET_GEM_VERSION: 6.1.0

# Puppet 6.2.0 Unit test:
#   extends: .unit_test
#   variables:
#     PUPPET_GEM_VERSION: 6.2.0

# Puppet 6.3.0 Unit test:
#   extends: .unit_test
#   variables:
#     PUPPET_GEM_VERSION: 6.3.0

# Puppet 6.4.0 Unit test:
#   extends: .unit_test
#   variables:
#     PUPPET_GEM_VERSION: 6.4.0

# Puppet 6.5.0 Unit test:
#   extends: .unit_test
#   variables:
#     PUPPET_GEM_VERSION: 6.4.0

# Puppet 6.6.0 Unit test:
#   extends: .unit_test
#   variables:
#     PUPPET_GEM_VERSION: 6.6.0

# Puppet 6.7.0 Unit test:
#   extends: .unit_test
#   variables:
#     PUPPET_GEM_VERSION: 6.7.2
