---
CommitMsg:
  CapitalizedSubject:
    enabled: false
  EmptyMessage:
    enabled: false
  TrailingPeriod:
    enabled: true
  TextWidth:
    enabled: false
PreCommit:
  ALL:
    on_warn: fail
  PuppetMetadataJsonLint:
    enabled: true
  AuthorEmail:
    enabled: true
  AuthorName:
    enabled: true
  MergeConflicts:
    enabled: true
  CaseConflicts:
    enabled: false
  PuppetLint:
    enabled: false
  YamlSyntax:
    enabled: false
  RuboCop:
    enabled: true
  Fasterer:
    enabled: true
  Brakeman:
    enabled: true
PrePush:
  RakeTarget:
    enabled: true
    description: Run RSpec tests
    targets:
    - spec
