require: rubocop-performance
# Common configuration.
AllCops:
  # Include common Ruby source files.

  Include:
    - '**/*.rb'

  Exclude:
    - '**/.identity.rb'
    - '**/*.rake'
    - '**/*.task'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/jwt.rb'
    - '**/preamble.rb'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - 'bin/*'
    - 'bin/**/*'
    - 'lib/1.8.7/csv.rb'
    - 'lib/connect/lexer.rb'
    - 'lib/connect/parser.rb'
    - 'lib/racc/**/*'
    - 'pkg/**/*'
    - 'spec/**/*.rb'
    - 'spec/**/*'

Style/SafeNavigation:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

# Ruby 1.8.7 doesn't have the -> lambda
Style/Lambda:
  Enabled: false

# Ruby 1.8.7 doesn't have 1.9 style hash syntax
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SignalException:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Eval:
  Enabled: false

LineLength:
  Max: 200

AccessorMethodName:
  Enabled: false

MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false
