language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  # - 2.2.0
bundler_args: --without development
script:
  - bundle exec rake spec
gemfile:
  - gemfiles/gemfile.1.8.7
  - gemfiles/gemfile.1.9.3

env:
  # - PUPPET_GEM_VERSION=3.0.2
  # - PUPPET_GEM_VERSION=3.1.1
  # - PUPPET_GEM_VERSION=3.2.4
  # - PUPPET_GEM_VERSION=3.3.2
  - PUPPET_GEM_VERSION=3.4.3
  - PUPPET_GEM_VERSION=3.5.1
  - PUPPET_GEM_VERSION=3.6.2
  - PUPPET_GEM_VERSION=3.7.3
  - PUPPET_GEM_VERSION=4.0.0

sudo:   false
cache:  bundler

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/gemfile.1.9.3
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=4.0.0
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile.1.8.7
    - rvm: 2.0.0
      gemfile: gemfiles/gemfile.1.8.7
    - rvm: 2.1.0
      gemfile: gemfiles/gemfile.1.8.7
