language: ruby
rvm:
  - 1.8.7
  - ruby-1.9.3-p551
  - ruby-2.0.0-p648
  - 2.1.10
script:
  - bundle exec rake spec

env:
  - PUPPET_GEM_VERSION=3.4.3 HIERA_GEM_VERSION=1.3.4
  - PUPPET_GEM_VERSION=3.5.1 HIERA_GEM_VERSION=1.3.4
  - PUPPET_GEM_VERSION=3.6.2 HIERA_GEM_VERSION=1.3.4
  - PUPPET_GEM_VERSION=3.7.3 HIERA_GEM_VERSION=1.3.4
  - PUPPET_GEM_VERSION=4.0.0 HIERA_GEM_VERSION=2.0.0
  - PUPPET_GEM_VERSION=4.1.0 HIERA_GEM_VERSION=2.0.0
  - PUPPET_GEM_VERSION=4.2.3 HIERA_GEM_VERSION=2.0.0
  - PUPPET_GEM_VERSION=4.3.2 HIERA_GEM_VERSION=3.1.1
  - PUPPET_GEM_VERSION=4.4.1 HIERA_GEM_VERSION=3.1.1

sudo:   false
cache:  bundler

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/gemfile.1.9.3
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=4.0.0 HIERA_GEM_VERSION=2.0.0
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=4.1.0 HIERA_GEM_VERSION=2.0.0
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=4.2.3 HIERA_GEM_VERSION=2.0.0
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=4.3.2 HIERA_GEM_VERSION=3.1.1
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=4.4.1 HIERA_GEM_VERSION=3.1.1
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile.1.8.7
    - rvm: 2.0.0
      gemfile: gemfiles/gemfile.1.8.7
    - rvm: 2.1.0
      gemfile: gemfiles/gemfile.1.8.7
