#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative 'dsl'
  require_relative 'lexer'

class Dsl < Racc::Parser

module_eval(<<'...end dsl.y/module_eval...', 'dsl.y', 22)
  def parse(input)
    scan_str(input)
  end
...end dsl.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     8,     6,     6,    14,    15,    10,     7,     7,    11,    12,
    13,    16 ]

racc_action_check = [
     1,     0,     1,    10,    10,     6,     0,     1,     6,     7,
     8,    11 ]

racc_action_pointer = [
    -1,     0,   nil,   nil,   nil,   nil,     2,     5,    10,   nil,
    -1,     9,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -10,   -10,    -1,    -3,    -4,    -5,   -10,   -10,   -10,    -2,
   -10,   -10,    -9,    17,    -6,    -7,    -8 ]

racc_goto_table = [
     2,     9,     1 ]

racc_goto_check = [
     2,     2,     1 ]

racc_goto_pointer = [
   nil,     2,     0,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 9, :_reduce_none,
  2, 9, :_reduce_none,
  1, 10, :_reduce_none,
  1, 10, :_reduce_none,
  1, 10, :_reduce_none,
  3, 11, :_reduce_6,
  3, 11, :_reduce_7,
  3, 12, :_reduce_8,
  2, 13, :_reduce_9 ]

racc_reduce_n = 10

racc_shift_n = 17

racc_token_table = {
  false => 0,
  :error => 1,
  :FULL_IDENTIFIER => 2,
  :ASSIGNMENT => 3,
  :STRING => 4,
  :NUMBER => 5,
  :CONNECTION => 6,
  :INCLUDE => 7 }

racc_nt_base = 8

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "FULL_IDENTIFIER",
  "ASSIGNMENT",
  "STRING",
  "NUMBER",
  "CONNECTION",
  "INCLUDE",
  "$start",
  "dsl",
  "config",
  "assignment",
  "connection",
  "include_stmnt" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

module_eval(<<'.,.,', 'dsl.y', 5)
  def _reduce_6(val, _values, result)
     puts 'string assignment'
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 6)
  def _reduce_7(val, _values, result)
     puts 'number assignment'
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 9)
  def _reduce_8(val, _values, result)
     puts 'connection'
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 12)
  def _reduce_9(val, _values, result)
     puts 'include'
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Dsl
