#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require 'connect/extended_array'
  require 'connect/dsl'
  require 'connect/lexer'

module Connect
  class Dsl < Racc::Parser

module_eval(<<'...end dsl.y/module_eval...', 'dsl.y', 262)

  def parse(input)
    scan_str(input) unless empty_definition?(input)
  end

  def power(v1,v2)
    v1 ^ v2
  end

  def multiply(v1,v2)
    v1 * v2
  end

  def divide(v1,v2)
    v1 / v2
  end

  def add(v1,v2)
    v1 + v2
  end

  def subtract(v1,v2)
    v1 - v2
  end

  def do_or(v1,v2)
    v1 || v2
  end

  def do_and(v1,v2)
    v1 && v2
  end

  def on_error(token, value, vstack )
    position =  "Syntax error around line #{lineno} of config file '#{current_file}'"
    text = @ss.peek(20)
    unless value.nil?
      msg = "#{position} at value '#{value}' : #{text}"
    else
      msg = "#{position} at token '#{token}' : #{text}"
    end
    if @ss.eos?
      msg = "#{position}: Unexpected end of file"
    end
    raise ParseError, msg
  end
...end dsl.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    17,   115,     9,    10,    36,    37,     4,   134,     9,    10,
   134,   121,     4,   122,     9,    10,   135,   120,     4,   119,
     9,    10,   134,   159,     4,   -88,   -88,    39,    40,   -88,
   -88,    11,    96,   130,    14,   147,    16,    11,    81,   116,
    14,    82,    16,    11,    39,    40,    14,   132,    16,    11,
     9,    27,    14,   133,    16,   100,   124,    39,    40,   100,
     9,    44,    42,    43,    24,    25,    58,     9,    27,    24,
    25,    47,    48,     9,    44,    42,    43,    36,    37,    58,
   136,    57,    24,    25,    47,    48,   137,   153,     9,    27,
     9,    44,    42,    43,    57,    85,    58,    24,    25,    24,
    25,    47,    48,     9,    44,    42,    43,    36,    37,    58,
   100,    57,    24,    25,    47,    48,     9,    44,    42,    43,
    36,    37,    58,   139,    57,    24,    25,    47,    48,     9,
    44,    42,    43,    36,    37,    58,   140,    57,    24,    25,
    47,    48,     9,    44,    42,    43,     9,    27,    58,   100,
    57,    24,    25,    47,    48,     9,    44,    42,    43,    24,
    25,    58,    98,    57,    24,    25,    47,    48,     9,    44,
    42,    43,     9,    27,    58,    93,    57,    24,    25,    47,
    48,     9,    44,    42,    43,    68,    67,    58,    66,    57,
    24,    25,    47,    48,     9,    44,    42,    43,    63,   149,
    58,    60,    57,    24,    25,    47,    48,     9,    44,    42,
    43,    33,    32,    58,    23,    57,    24,    25,    47,    48,
     9,    44,    42,    43,    21,   154,    58,   155,    57,    24,
    25,    47,    48,     9,    44,    42,    43,   119,   157,    58,
   158,    57,    24,    25,    47,    48,     9,    44,    42,    43,
    20,   160,    58,    19,    57,    24,    25,    47,    48,     9,
    44,    42,    43,     9,    27,    58,   162,    57,    24,    25,
    47,    48,    24,    25,    89,    42,    43,   163,   nil,   nil,
    57,    87,    24,    25,    47,    48,    89,    42,    43,   nil,
    89,    42,    43,   nil,    24,    25,    47,    48,    24,    25,
    47,    48,    69,    70,    71,    72,    73,    74,    75,    81,
     9,    27,    82,   nil,     9,    27,   nil,   nil,   nil,    24,
    25,    39,    40 ]

racc_action_check = [
     1,    82,     1,     1,    64,    64,     1,   112,     0,     0,
   152,    91,     0,    91,    12,    12,   112,    89,    12,    86,
    22,    22,   126,   152,    22,   133,   133,    22,    22,   132,
   132,     1,    64,   100,     1,   126,     1,     0,    76,    83,
     0,    76,     0,    12,   156,   156,    12,   102,    12,    22,
   125,   125,    22,   103,    22,   133,    96,   125,   125,   132,
   137,   137,   137,   137,    14,    14,   137,    32,    32,   137,
   137,   137,   137,    57,    57,    57,    57,    21,    21,    57,
   113,   137,    57,    57,    57,    57,   115,   137,    68,    68,
   134,   134,   134,   134,    57,    57,   134,    68,    68,   134,
   134,   134,   134,    98,    98,    98,    98,   124,   124,    98,
    67,   134,    98,    98,    98,    98,   116,   116,   116,   116,
   101,   101,   116,   117,    98,   116,   116,   116,   116,    81,
    81,    81,    81,    99,    99,    81,   118,   116,    81,    81,
    81,    81,    75,    75,    75,    75,    15,    15,    75,    66,
    81,    75,    75,    75,    75,    23,    23,    23,    23,    63,
    63,    23,    65,    75,    23,    23,    23,    23,   136,   136,
   136,   136,    97,    97,   136,    60,    23,   136,   136,   136,
   136,    74,    74,    74,    74,    44,    35,    74,    34,   136,
    74,    74,    74,    74,    69,    69,    69,    69,    31,   130,
    69,    26,    74,    69,    69,    69,    69,    73,    73,    73,
    73,    17,    16,    73,    13,    69,    73,    73,    73,    73,
    70,    70,    70,    70,    11,   142,    70,   143,    73,    70,
    70,    70,    70,   123,   123,   123,   123,   148,   149,   123,
   151,    70,   123,   123,   123,   123,    71,    71,    71,    71,
    10,   153,    71,     9,   123,    71,    71,    71,    71,    72,
    72,    72,    72,    20,    20,    72,   160,    71,    72,    72,
    72,    72,    20,    20,    58,    58,    58,   162,   nil,   nil,
    72,    58,    58,    58,    58,    58,   119,   119,   119,   nil,
   129,   129,   129,   nil,   119,   119,   119,   119,   129,   129,
   129,   129,    56,    56,    56,    56,    56,    56,    56,    56,
   120,   120,    56,   nil,    29,    29,   nil,   nil,   nil,   120,
   120,    29,    29 ]

racc_action_pointer = [
     6,     0,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   250,
   223,   222,    12,   181,    53,   144,   175,   211,   nil,   nil,
   261,    70,    18,   153,   nil,   nil,   166,   nil,   nil,   312,
   nil,   165,    65,   nil,   160,   158,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   158,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   286,    71,   271,   nil,
   173,   nil,   nil,   148,    -3,   135,   112,    73,    86,   192,
   218,   244,   257,   205,   179,   140,    15,   nil,   nil,   nil,
   nil,   127,    -2,    24,   nil,   nil,     4,   nil,   nil,   -10,
   nil,   -19,   nil,   nil,   nil,   nil,    54,   170,   101,   126,
    29,   113,    19,    25,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    -8,    55,   nil,    59,   114,    99,   126,   283,
   308,   nil,   nil,   231,   100,    48,     7,   nil,   nil,   287,
   161,   nil,    22,    18,    88,   nil,   166,    58,   nil,   nil,
   nil,   nil,   197,   199,   nil,   nil,   nil,   nil,   222,   234,
   nil,   216,    -5,   221,   nil,   nil,    35,   nil,   nil,   nil,
   263,   nil,   249,   nil ]

racc_action_default = [
   -90,   -90,    -1,    -5,    -6,    -7,    -8,    -9,   -10,   -90,
   -16,   -90,   -90,   -90,   -90,   -90,   -90,   -90,    -2,   -15,
   -90,   -90,   -90,   -90,   -17,   -18,   -71,   -16,   -73,   -90,
   -81,   -90,   -90,   164,   -90,   -90,   -11,   -12,   -54,   -13,
   -14,   -55,    -3,    -4,   -16,   -19,   -20,   -21,   -22,   -23,
   -24,   -25,   -26,   -27,   -28,   -34,   -43,   -90,   -90,   -70,
   -90,   -76,   -80,   -90,   -90,   -79,   -88,   -88,   -90,   -90,
   -90,   -90,   -90,   -90,   -90,   -90,   -42,   -45,   -46,   -47,
   -48,   -90,   -90,   -60,   -30,   -57,   -60,   -59,   -62,   -64,
   -65,   -90,   -69,   -72,   -82,   -74,   -90,   -90,   -90,   -90,
   -90,   -90,   -90,   -90,   -35,   -36,   -37,   -38,   -39,   -40,
   -41,   -44,   -90,   -32,   -33,   -51,   -61,   -90,   -90,   -61,
   -90,   -66,   -67,   -90,   -90,   -90,   -90,   -32,   -83,   -90,
   -90,   -84,   -86,   -85,   -90,   -49,   -90,   -90,   -29,   -56,
   -58,   -63,   -90,   -90,   -68,   -75,   -77,   -78,   -60,   -90,
   -31,   -90,   -90,   -90,   -85,   -86,   -90,   -89,   -50,   -52,
   -90,   -87,   -90,   -53 ]

racc_goto_table = [
    41,    13,    13,    26,    38,    62,    59,    61,    29,    34,
    90,    92,    86,    13,   101,   113,    31,   112,    18,   117,
     1,    35,   118,    13,     7,     7,    95,   128,    77,   131,
    31,    64,    22,    65,   126,    28,     7,    76,    83,    18,
    84,   123,   141,   nil,   nil,   nil,     7,    97,   111,   nil,
   nil,   nil,    94,   nil,   nil,   nil,   nil,   102,   104,   105,
   106,   107,   108,   109,   110,   nil,   nil,   nil,   150,   103,
   151,    90,    92,   152,   nil,   nil,   nil,   nil,   nil,   nil,
   101,    90,    92,   148,   156,   nil,   nil,   nil,   nil,   nil,
   125,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    31,   138,
   nil,    62,   nil,   146,   nil,   nil,   144,   145,   nil,   143,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   142,   nil,   nil,   nil,   nil,    31,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   161 ]

racc_goto_check = [
    10,    11,    11,    12,     9,    39,    20,    10,    38,    12,
    13,    17,    30,    11,    40,    22,    11,    21,     2,    29,
     1,    11,    29,    11,     7,     7,    37,    41,    24,    41,
    11,    36,     1,    11,    21,    35,     7,    23,    19,     2,
    20,    33,    31,   nil,   nil,   nil,     7,     9,    24,   nil,
   nil,   nil,    12,   nil,   nil,   nil,   nil,    12,    14,    14,
    14,    14,    14,    14,    14,   nil,   nil,   nil,    22,    11,
    22,    13,    17,    21,   nil,   nil,   nil,   nil,   nil,   nil,
    40,    13,    17,    30,    29,   nil,   nil,   nil,   nil,   nil,
    38,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11,    20,
   nil,    39,   nil,    10,   nil,   nil,    20,     9,   nil,    12,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    11,   nil,   nil,   nil,   nil,    11,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    10 ]

racc_goto_pointer = [
   nil,    20,    17,   nil,   nil,   nil,   nil,    24,   nil,   -17,
   -22,     1,   -11,   -48,   -11,   nil,   nil,   -47,   nil,   -19,
   -17,   -64,   -66,   -19,   -28,   nil,   nil,   nil,   nil,   -64,
   -46,   -77,   nil,   -50,   nil,    20,    -1,   -38,    -7,   -24,
   -53,   -72 ]

racc_goto_default = [
   nil,   nil,     2,    46,     3,     5,     6,    52,     8,   129,
   nil,    55,    45,    49,    56,    50,    51,    53,    54,   nil,
   114,   nil,   127,   nil,   nil,    78,    79,    80,    12,   nil,
   nil,    88,    91,   nil,    15,   nil,   nil,   nil,   nil,    30,
    99,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 40, :_reduce_none,
  2, 40, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 48, :_reduce_none,
  1, 48, :_reduce_none,
  1, 49, :_reduce_none,
  1, 49, :_reduce_none,
  2, 50, :_reduce_15,
  1, 50, :_reduce_16,
  1, 51, :_reduce_17,
  1, 51, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 53, :_reduce_none,
  1, 53, :_reduce_none,
  1, 53, :_reduce_none,
  1, 53, :_reduce_none,
  1, 53, :_reduce_none,
  1, 53, :_reduce_none,
  3, 58, :_reduce_29,
  1, 58, :_reduce_30,
  3, 60, :_reduce_31,
  1, 60, :_reduce_32,
  1, 61, :_reduce_none,
  1, 57, :_reduce_34,
  3, 59, :_reduce_35,
  3, 59, :_reduce_36,
  3, 59, :_reduce_37,
  3, 59, :_reduce_38,
  3, 59, :_reduce_39,
  3, 59, :_reduce_40,
  3, 59, :_reduce_41,
  2, 59, :_reduce_42,
  1, 59, :_reduce_none,
  2, 62, :_reduce_44,
  1, 62, :_reduce_none,
  1, 63, :_reduce_none,
  1, 63, :_reduce_none,
  1, 63, :_reduce_none,
  3, 64, :_reduce_49,
  5, 64, :_reduce_50,
  2, 65, :_reduce_51,
  5, 65, :_reduce_52,
  7, 66, :_reduce_53,
  3, 67, :_reduce_54,
  3, 47, :_reduce_55,
  4, 54, :_reduce_56,
  2, 54, :_reduce_57,
  4, 55, :_reduce_58,
  2, 55, :_reduce_59,
  0, 68, :_reduce_none,
  1, 68, :_reduce_none,
  1, 69, :_reduce_none,
  3, 69, :_reduce_63,
  1, 71, :_reduce_64,
  1, 71, :_reduce_none,
  1, 72, :_reduce_none,
  1, 72, :_reduce_none,
  3, 70, :_reduce_68,
  1, 70, :_reduce_69,
  3, 43, :_reduce_70,
  2, 44, :_reduce_71,
  4, 44, :_reduce_72,
  2, 45, :_reduce_none,
  4, 45, :_reduce_none,
  6, 73, :_reduce_75,
  2, 74, :_reduce_76,
  3, 76, :_reduce_none,
  4, 75, :_reduce_78,
  1, 75, :_reduce_79,
  2, 77, :_reduce_none,
  1, 77, :_reduce_none,
  3, 78, :_reduce_82,
  6, 46, :_reduce_83,
  6, 46, :_reduce_84,
  4, 56, :_reduce_85,
  4, 56, :_reduce_86,
  4, 80, :_reduce_87,
  0, 79, :_reduce_none,
  4, 79, :_reduce_89 ]

racc_reduce_n = 90

racc_shift_n = 164

racc_token_table = {
  false => 0,
  :error => 1,
  :SCOPE => 2,
  :IDENTIFIER => 3,
  :INTEGER => 4,
  :FLOAT => 5,
  :connection => 6,
  :DO => 7,
  "{" => 8,
  :END => 9,
  "}" => 10,
  :DOUBLE_QUOTED => 11,
  :SINGLE_QUOTED => 12,
  :BOOLEAN => 13,
  :UNDEF => 14,
  "," => 15,
  "^" => 16,
  "*" => 17,
  "/" => 18,
  "+" => 19,
  "-" => 20,
  :OR => 21,
  :AND => 22,
  "[" => 23,
  "]" => 24,
  :DOUBLE_DOTS => 25,
  "." => 26,
  "(" => 27,
  ")" => 28,
  "&" => 29,
  ":" => 30,
  :WITH => 31,
  :HASH_ROCKET => 32,
  "=" => 33,
  :INCLUDE => 34,
  :INTO => 35,
  :IMPORT => 36,
  :FROM => 37,
  :TO => 38 }

racc_nt_base = 39

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SCOPE",
  "IDENTIFIER",
  "INTEGER",
  "FLOAT",
  "connection",
  "DO",
  "\"{\"",
  "END",
  "\"}\"",
  "DOUBLE_QUOTED",
  "SINGLE_QUOTED",
  "BOOLEAN",
  "UNDEF",
  "\",\"",
  "\"^\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "OR",
  "AND",
  "\"[\"",
  "\"]\"",
  "DOUBLE_DOTS",
  "\".\"",
  "\"(\"",
  "\")\"",
  "\"&\"",
  "\":\"",
  "WITH",
  "HASH_ROCKET",
  "\"=\"",
  "INCLUDE",
  "INTO",
  "IMPORT",
  "FROM",
  "TO",
  "$start",
  "dsl",
  "config",
  "number",
  "assignment",
  "include",
  "import",
  "object_definition",
  "with",
  "block_begin",
  "block_end",
  "literal",
  "string",
  "scalar",
  "value",
  "array",
  "hash",
  "object_reference",
  "reference",
  "values",
  "expression",
  "parameters",
  "parameter",
  "selectors",
  "selector",
  "array_selector",
  "function_selector",
  "special_selector",
  "with_scope_do",
  "optional_comma",
  "hashpairs",
  "hashpair",
  "hashkey",
  "hash_seperator",
  "import_with_scope_begin",
  "import_with_scope_end",
  "datasource",
  "import_block",
  "import_statements",
  "import_statement",
  "iterator",
  "definition_block" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'dsl.y', 42)
  def _reduce_15(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 43)
  def _reduce_16(val, _values, result)
     result = "#{val[0]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 47)
  def _reduce_17(val, _values, result)
     result = interpolate(val[0], xref)
    result
  end
.,.,

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'dsl.y', 68)
  def _reduce_29(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 69)
  def _reduce_30(val, _values, result)
     result = ExtendedArray[val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 73)
  def _reduce_31(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 74)
  def _reduce_32(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

# reduce 33 omitted

module_eval(<<'.,.,', 'dsl.y', 82)
  def _reduce_34(val, _values, result)
    result = reference(val[0], xref)
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 86)
  def _reduce_35(val, _values, result)
     result = power(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 87)
  def _reduce_36(val, _values, result)
     result = multiply(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 88)
  def _reduce_37(val, _values, result)
     result = divide(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 89)
  def _reduce_38(val, _values, result)
     result = add(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 90)
  def _reduce_39(val, _values, result)
     result = subtract(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 91)
  def _reduce_40(val, _values, result)
     result = do_or(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 92)
  def _reduce_41(val, _values, result)
     result = do_and(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 93)
  def _reduce_42(val, _values, result)
     result = selector(val[0], val[1])
    result
  end
.,.,

# reduce 43 omitted

module_eval(<<'.,.,', 'dsl.y', 101)
  def _reduce_44(val, _values, result)
     result = val.join
    result
  end
.,.,

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

module_eval(<<'.,.,', 'dsl.y', 112)
  def _reduce_49(val, _values, result)
     result = "[#{to_param(val[1])}]" 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 113)
  def _reduce_50(val, _values, result)
     result = "[#{to_param(val[1])}..#{to_param(val[3])}]" 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 117)
  def _reduce_51(val, _values, result)
     result = val.join
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 118)
  def _reduce_52(val, _values, result)
     result = val[0] + val[1] + val[2] + to_param(val[3]) +  val[4]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 122)
  def _reduce_53(val, _values, result)
     result = val.join
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 129)
  def _reduce_54(val, _values, result)
     push_scope(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 133)
  def _reduce_55(val, _values, result)
     pop_scope 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 140)
  def _reduce_56(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 141)
  def _reduce_57(val, _values, result)
     result = ExtendedArray[]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 148)
  def _reduce_58(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 149)
  def _reduce_59(val, _values, result)
     result = MethodHash.new
    result
  end
.,.,

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

module_eval(<<'.,.,', 'dsl.y', 159)
  def _reduce_63(val, _values, result)
     result.merge!(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 163)
  def _reduce_64(val, _values, result)
     result = val[0]
    result
  end
.,.,

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

module_eval(<<'.,.,', 'dsl.y', 173)
  def _reduce_68(val, _values, result)
     result = MethodHash[val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 174)
  def _reduce_69(val, _values, result)
     result = MethodHash[val[0].object_id, val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 181)
  def _reduce_70(val, _values, result)
     assign(val[0], val[2], xdef)
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 189)
  def _reduce_71(val, _values, result)
     include_file(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 190)
  def _reduce_72(val, _values, result)
     include_file(val[1], val[3])
    result
  end
.,.,

# reduce 73 omitted

# reduce 74 omitted

module_eval(<<'.,.,', 'dsl.y', 202)
  def _reduce_75(val, _values, result)
     push_scope(val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 206)
  def _reduce_76(val, _values, result)
     pop_scope
    result
  end
.,.,

# reduce 77 omitted

module_eval(<<'.,.,', 'dsl.y', 213)
  def _reduce_78(val, _values, result)
     datasource( val[0], *val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 214)
  def _reduce_79(val, _values, result)
     datasource( val[0], *[])
    result
  end
.,.,

# reduce 80 omitted

# reduce 81 omitted

module_eval(<<'.,.,', 'dsl.y', 223)
  def _reduce_82(val, _values, result)
     import(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 231)
  def _reduce_83(val, _values, result)
     result = define_object(val[0], val[2], val[5], val[4], xdef)
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 233)
  def _reduce_84(val, _values, result)
     result = define_object(val[0], lookup_value(val[2]), val[5], val[4], xdef)
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 238)
  def _reduce_85(val, _values, result)
     result = reference_object(val[0], lookup_value(val[2]), xref)
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 239)
  def _reduce_86(val, _values, result)
     result = reference_object(val[0], val[2], xref)
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 245)
  def _reduce_87(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 88 omitted

module_eval(<<'.,.,', 'dsl.y', 250)
  def _reduce_89(val, _values, result)
     result = {:from => val[1], :to => val[3]}
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Dsl
  end   # module Connect
