#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require 'connect/dsl'
  require 'connect/lexer'

module Connect
  class Dsl < Racc::Parser

module_eval(<<'...end dsl.y/module_eval...', 'dsl.y', 194)

  def parse(input)
    scan_str(input) unless empty_definition?(input)
  end

  def power(v1,v2)
    v1 ^ v2
  end

  def multiply(v1,v2)
    v1 * v2
  end

  def divide(v1,v2)
    v1 / v2
  end

  def add(v1,v2)
    v1 + v2
  end

  def subtract(v1,v2)
    v1 - v2
  end

  def do_or(v1,v2)
    v1 || v2
  end

  def do_and(v1,v2)
    v1 && v2
  end

  def on_error(token, value, vstack )
    position =  "Syntax error on line #{lineno} of config file '#{current_file}'"
    text = @ss.peek(20)
    unless value.nil?
      msg = "#{position} at value '#{value}' : #{text}"
    else
      msg = "#{position} at token '#{token}' : #{text}"
    end
    if @ss.eos?
      msg = "#{position}: Unexpected end of file"
    end
    raise ParseError, msg
  end
...end dsl.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    17,   131,    12,    13,    12,    13,    22,     9,   132,     9,
    12,    13,   110,    38,    98,     9,    12,    13,    12,    13,
    57,     9,    99,     9,   109,   108,   109,   108,   102,    15,
    23,    15,    56,    16,   105,    16,   106,    15,   103,   104,
    58,    16,    34,    15,    59,    15,    23,    16,   112,    16,
    12,    13,    12,    29,    24,     9,    35,    36,    37,    12,
    29,    12,    13,    41,    42,    28,    29,    23,    53,    25,
    26,    25,    26,    45,    46,    25,    26,    15,    25,    26,
    30,    16,    52,    71,    12,    13,    41,    42,   116,   117,
    87,    53,    22,    19,    25,    26,    45,    46,    87,    12,
    13,    41,    42,   126,    83,    52,    53,    80,   129,    25,
    26,    45,    46,    98,    12,    13,    41,    42,    80,   102,
    52,    53,   102,   135,    25,    26,    45,    46,   136,    12,
    13,    41,    42,    60,   138,    52,    53,   139,   nil,    25,
    26,    45,    46,    90,    41,    42,   nil,   nil,   nil,    53,
    52,   nil,    25,    26,    45,    46,    90,    41,    42,   nil,
   nil,   nil,    53,    52,   nil,    25,    26,    45,    46,    90,
    41,    42,   nil,   nil,   nil,    53,    52,   nil,    25,    26,
    45,    46,    90,    41,    42,   nil,   nil,   nil,    53,    52,
   nil,    25,    26,    45,    46,    90,    41,    42,   nil,   nil,
   nil,    53,    52,   nil,    25,    26,    45,    46,    90,    41,
    42,   nil,   nil,   nil,    53,    52,   nil,    25,    26,    45,
    46,    90,    41,    42,   nil,   nil,   nil,    53,    52,   nil,
    25,    26,    45,    46,    90,    41,    42,   nil,   nil,   nil,
    53,    52,   nil,    25,    26,    45,    46,    76,    41,    42,
   nil,    76,    41,    42,    52,   nil,    25,    26,    45,    46,
    25,    26,    45,    46,    76,    41,    42,   nil,    76,    41,
    42,   nil,    74,    25,    26,    45,    46,    25,    26,    45,
    46,    41,    42,   nil,   nil,    41,    42,   nil,   nil,    25,
    26,    45,    46,    25,    26,    45,    46,    61,    62,    63,
    64,    65,    66,    67 ]

racc_action_check = [
     1,   124,     1,     1,    21,    21,    28,     1,   124,    21,
     0,     0,    87,    21,    69,     0,    10,    10,    11,    11,
    28,    10,    70,    11,    88,    88,    86,    86,    73,     1,
    76,    21,    27,     1,    84,    21,    85,     0,    78,    78,
    33,     0,    17,    10,    39,    11,    90,    10,    97,    11,
    20,    20,    58,    58,    14,    20,    19,    19,    20,    23,
    23,    52,    52,    52,    52,    16,    16,    13,    52,    23,
    23,    52,    52,    52,    52,    16,    16,    20,    15,    15,
    16,    20,    52,    52,    24,    24,    24,    24,   100,   101,
    60,    24,    12,     9,    24,    24,    24,    24,    59,    98,
    98,    98,    98,   106,    56,    24,    98,    55,   110,    98,
    98,    98,    98,   115,   104,   104,   104,   104,    54,   127,
    98,   104,   128,   129,   104,   104,   104,   104,   130,   103,
   103,   103,   103,    40,   133,   104,   103,   134,   nil,   103,
   103,   103,   103,    66,    66,    66,   nil,   nil,   nil,    66,
   103,   nil,    66,    66,    66,    66,    65,    65,    65,   nil,
   nil,   nil,    65,    66,   nil,    65,    65,    65,    65,    61,
    61,    61,   nil,   nil,   nil,    61,    65,   nil,    61,    61,
    61,    61,    64,    64,    64,   nil,   nil,   nil,    64,    61,
   nil,    64,    64,    64,    64,    67,    67,    67,   nil,   nil,
   nil,    67,    64,   nil,    67,    67,    67,    67,    62,    62,
    62,   nil,   nil,   nil,    62,    67,   nil,    62,    62,    62,
    62,    99,    99,    99,   nil,   nil,   nil,    99,    62,   nil,
    99,    99,    99,    99,    63,    63,    63,   nil,   nil,   nil,
    63,    99,   nil,    63,    63,    63,    63,   102,   102,   102,
   nil,   108,   108,   108,    63,   nil,   102,   102,   102,   102,
   108,   108,   108,   108,    53,    53,    53,   nil,   109,   109,
   109,   nil,    53,    53,    53,    53,    53,   109,   109,   109,
   109,   105,   105,   nil,   nil,   131,   131,   nil,   nil,   105,
   105,   105,   105,   131,   131,   131,   131,    51,    51,    51,
    51,    51,    51,    51 ]

racc_action_pointer = [
     8,     0,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    91,
    14,    16,    89,    36,    26,    66,    63,    42,   nil,    48,
    48,     2,   nil,    57,    82,   nil,   nil,     2,     3,   nil,
   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,   nil,    12,
   101,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   281,    59,   261,   112,   101,   102,   nil,    50,    64,
    56,   166,   205,   231,   179,   153,   140,   192,   nil,   -11,
    -3,   nil,   nil,     3,   nil,   nil,    -1,   nil,    12,   nil,
   nil,   nil,   nil,   nil,     3,     6,    18,     8,    16,   nil,
    15,   nil,   nil,   nil,   nil,   nil,   nil,    24,    97,   218,
    64,    78,   244,   127,   112,   277,   101,   nil,   248,   265,
    73,   nil,   nil,   nil,   nil,    88,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   -24,   nil,   nil,    94,    97,   119,
   104,   281,   nil,   123,   127,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -80,   -80,    -1,    -5,    -6,    -7,    -8,    -9,   -10,   -80,
   -80,   -80,   -80,   -18,   -80,   -80,   -80,   -80,    -2,   -80,
   -80,   -80,   -17,   -80,   -80,   -19,   -20,   -60,   -80,   -18,
   -67,   -68,   -70,   -80,   140,   -13,   -14,   -15,   -16,   -80,
   -80,    -3,    -4,   -21,   -22,   -23,   -24,   -25,   -26,   -27,
   -28,   -37,   -80,   -80,   -11,   -11,   -80,   -69,   -80,   -78,
   -78,   -80,   -80,   -80,   -80,   -80,   -80,   -80,   -29,   -44,
   -44,   -41,   -57,   -44,   -43,   -46,   -48,   -49,   -80,   -54,
   -12,   -58,   -59,   -61,   -66,   -72,   -75,   -80,   -75,   -30,
   -80,   -31,   -32,   -33,   -34,   -35,   -36,   -80,   -45,   -45,
   -80,   -80,   -45,   -80,   -80,   -80,   -80,   -73,   -80,   -80,
   -80,   -74,   -38,   -55,   -56,   -44,   -40,   -42,   -47,   -50,
   -52,   -51,   -53,   -62,   -80,   -64,   -71,   -44,   -44,   -80,
   -80,   -80,   -65,   -80,   -80,   -79,   -39,   -63,   -76,   -77 ]

racc_goto_table = [
     7,     7,   125,    97,   100,    31,    18,   101,    73,   124,
     7,     7,    40,    55,    86,    88,    77,    51,    85,    69,
     7,     7,     1,    70,    33,    18,    18,   118,   137,    27,
    32,    54,    20,    21,   107,   nil,   111,    39,    81,    82,
   nil,    68,   nil,   nil,   nil,   nil,   nil,    84,   nil,   130,
   nil,   nil,   nil,    79,    89,    91,    92,    93,    94,    95,
    96,   133,   134,   127,   128,    77,   115,   nil,   123,   114,
   nil,    77,    77,   nil,   120,   122,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,   nil,
   nil,   113,    68,    68,   123,   nil,   119,   121,   nil,   nil,
   nil,   nil,    79,   nil,   nil,   nil,   nil,   nil,    79,    79 ]

racc_goto_check = [
     8,     8,    26,    22,    22,    13,     2,    22,    23,    27,
     8,     8,    13,    13,    30,    30,    15,    16,    28,    21,
     8,     8,     1,    19,    29,     2,     2,    24,    26,    14,
    14,    20,     1,     1,    31,   nil,    31,    14,    10,    10,
   nil,    13,   nil,   nil,   nil,   nil,   nil,    13,   nil,    22,
   nil,   nil,   nil,     8,    16,    16,    16,    16,    16,    16,
    16,    22,    22,    23,    23,    15,    21,   nil,    15,    19,
   nil,    15,    15,   nil,    19,    19,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    13,   nil,   nil,
   nil,    16,    13,    13,    15,   nil,    16,    16,   nil,   nil,
   nil,   nil,     8,   nil,   nil,   nil,   nil,   nil,     8,     8 ]

racc_goto_pointer = [
   nil,    22,     5,   nil,   nil,   nil,   nil,   nil,     0,   nil,
   -16,   nil,   nil,   -11,    14,   -37,    -7,   nil,   nil,   -29,
     7,   -33,   -66,   -45,   -75,   nil,  -103,   -96,   -40,     8,
   -45,   -52 ]

racc_goto_default = [
   nil,   nil,     2,    44,     3,     4,     5,     6,    50,     8,
   nil,    10,    11,    14,    43,    47,    72,    48,    49,   nil,
   nil,   nil,   nil,   nil,    75,    78,   nil,   nil,   nil,   nil,
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 37, :_reduce_none,
  2, 37, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  0, 46, :_reduce_none,
  1, 46, :_reduce_none,
  3, 47, :_reduce_13,
  3, 48, :_reduce_14,
  3, 45, :_reduce_15,
  3, 45, :_reduce_16,
  2, 49, :_reduce_17,
  1, 49, :_reduce_18,
  1, 50, :_reduce_19,
  1, 50, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 55, :_reduce_29,
  3, 56, :_reduce_30,
  3, 56, :_reduce_31,
  3, 56, :_reduce_32,
  3, 56, :_reduce_33,
  3, 56, :_reduce_34,
  3, 56, :_reduce_35,
  3, 56, :_reduce_36,
  1, 56, :_reduce_none,
  4, 53, :_reduce_38,
  6, 53, :_reduce_39,
  4, 53, :_reduce_40,
  2, 53, :_reduce_41,
  4, 54, :_reduce_42,
  2, 54, :_reduce_43,
  0, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 59, :_reduce_none,
  3, 59, :_reduce_47,
  1, 61, :_reduce_48,
  1, 61, :_reduce_none,
  3, 60, :_reduce_50,
  3, 60, :_reduce_51,
  3, 60, :_reduce_52,
  3, 60, :_reduce_53,
  1, 60, :_reduce_54,
  3, 57, :_reduce_55,
  3, 57, :_reduce_56,
  1, 57, :_reduce_57,
  4, 40, :_reduce_58,
  4, 41, :_reduce_59,
  2, 42, :_reduce_60,
  4, 42, :_reduce_61,
  1, 62, :_reduce_none,
  3, 63, :_reduce_63,
  1, 63, :_reduce_64,
  4, 64, :_reduce_65,
  1, 64, :_reduce_66,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  2, 65, :_reduce_69,
  1, 65, :_reduce_none,
  6, 43, :_reduce_71,
  4, 43, :_reduce_72,
  6, 44, :_reduce_73,
  6, 44, :_reduce_74,
  0, 67, :_reduce_none,
  4, 67, :_reduce_76,
  4, 67, :_reduce_77,
  0, 66, :_reduce_none,
  4, 66, :_reduce_79 ]

racc_reduce_n = 80

racc_shift_n = 140

racc_token_table = {
  false => 0,
  :error => 1,
  :SCOPE => 2,
  :IDENTIFIER => 3,
  :INTEGER => 4,
  :FLOAT => 5,
  :SELECTOR => 6,
  :WITH => 7,
  :DO => 8,
  "{" => 9,
  :END => 10,
  "}" => 11,
  :DOUBLE_QUOTED => 12,
  :SINGLE_QUOTED => 13,
  :BOOLEAN => 14,
  :UNDEF => 15,
  "^" => 16,
  "*" => 17,
  "/" => 18,
  "+" => 19,
  "-" => 20,
  :OR => 21,
  :AND => 22,
  "[" => 23,
  "]" => 24,
  "," => 25,
  ":" => 26,
  :HASH_ROCKET => 27,
  "=" => 28,
  :INCLUDE => 29,
  :INTO => 30,
  "(" => 31,
  ")" => 32,
  :IMPORT => 33,
  :FROM => 34,
  :TO => 35 }

racc_nt_base = 36

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SCOPE",
  "IDENTIFIER",
  "INTEGER",
  "FLOAT",
  "SELECTOR",
  "WITH",
  "DO",
  "\"{\"",
  "END",
  "\"}\"",
  "DOUBLE_QUOTED",
  "SINGLE_QUOTED",
  "BOOLEAN",
  "UNDEF",
  "\"^\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "OR",
  "AND",
  "\"[\"",
  "\"]\"",
  "\",\"",
  "\":\"",
  "HASH_ROCKET",
  "\"=\"",
  "INCLUDE",
  "INTO",
  "\"(\"",
  "\")\"",
  "IMPORT",
  "FROM",
  "TO",
  "$start",
  "dsl",
  "config",
  "number",
  "assignment",
  "connection",
  "include_file",
  "import_data",
  "definition",
  "default_scope",
  "selector",
  "with_scope_do",
  "with_scope_bracket",
  "literal",
  "string",
  "scalar",
  "value",
  "array",
  "hash",
  "reference",
  "expression",
  "values",
  "optional_comma",
  "hashpairs",
  "hashpair",
  "hashkey",
  "parameter",
  "parameters",
  "datasource",
  "imported_name",
  "iterator",
  "block" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

module_eval(<<'.,.,', 'dsl.y', 34)
  def _reduce_13(val, _values, result)
     push_scope(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 38)
  def _reduce_14(val, _values, result)
     push_scope(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 43)
  def _reduce_15(val, _values, result)
     pop_scope 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 44)
  def _reduce_16(val, _values, result)
     pop_scope 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 49)
  def _reduce_17(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 50)
  def _reduce_18(val, _values, result)
     result = "#{val[0]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 54)
  def _reduce_19(val, _values, result)
     result = interpolate(val[0])
    result
  end
.,.,

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'dsl.y', 73)
  def _reduce_29(val, _values, result)
    result = reference(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 77)
  def _reduce_30(val, _values, result)
     result = power(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 78)
  def _reduce_31(val, _values, result)
     result = multiply(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 79)
  def _reduce_32(val, _values, result)
     result = divide(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 80)
  def _reduce_33(val, _values, result)
     result = add(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 81)
  def _reduce_34(val, _values, result)
     result = subtract(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 82)
  def _reduce_35(val, _values, result)
     result = do_or(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 83)
  def _reduce_36(val, _values, result)
     result = do_and(val[0],val[2])
    result
  end
.,.,

# reduce 37 omitted

module_eval(<<'.,.,', 'dsl.y', 88)
  def _reduce_38(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 89)
  def _reduce_39(val, _values, result)
     result = val[3].unshift(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 90)
  def _reduce_40(val, _values, result)
     result = [val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 91)
  def _reduce_41(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 95)
  def _reduce_42(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 96)
  def _reduce_43(val, _values, result)
     result = MethodHash.new
    result
  end
.,.,

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

module_eval(<<'.,.,', 'dsl.y', 106)
  def _reduce_47(val, _values, result)
     result.merge!(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 110)
  def _reduce_48(val, _values, result)
     result = val[0].to_sym
    result
  end
.,.,

# reduce 49 omitted

module_eval(<<'.,.,', 'dsl.y', 115)
  def _reduce_50(val, _values, result)
     result = MethodHash[val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 116)
  def _reduce_51(val, _values, result)
     result = MethodHash[val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 117)
  def _reduce_52(val, _values, result)
     result = MethodHash[val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 118)
  def _reduce_53(val, _values, result)
     result = MethodHash[val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 119)
  def _reduce_54(val, _values, result)
     result = MethodHash[val[0].object_id, val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 123)
  def _reduce_55(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 124)
  def _reduce_56(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 125)
  def _reduce_57(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 129)
  def _reduce_58(val, _values, result)
     assign(val[0], val[2], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 133)
  def _reduce_59(val, _values, result)
     connect(val[0], val[2], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 137)
  def _reduce_60(val, _values, result)
     include_file(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 138)
  def _reduce_61(val, _values, result)
     include_file(val[1], val[3])
    result
  end
.,.,

# reduce 62 omitted

module_eval(<<'.,.,', 'dsl.y', 146)
  def _reduce_63(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 147)
  def _reduce_64(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 151)
  def _reduce_65(val, _values, result)
     result = [val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 152)
  def _reduce_66(val, _values, result)
     result = [val[0], []]
    result
  end
.,.,

# reduce 67 omitted

# reduce 68 omitted

module_eval(<<'.,.,', 'dsl.y', 158)
  def _reduce_69(val, _values, result)
    result = "#{val[0]}*"
    result
  end
.,.,

# reduce 70 omitted

module_eval(<<'.,.,', 'dsl.y', 163)
  def _reduce_71(val, _values, result)
     import(val[1], val[5], val[3][0], val[3][1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 164)
  def _reduce_72(val, _values, result)
     import(val[1], nil, val[3][0], val[3][1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 170)
  def _reduce_73(val, _values, result)
     result = define(val[0], val[2], val[5], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 172)
  def _reduce_74(val, _values, result)
     result = define(val[0], val[2], val[5], val[4])
    result
  end
.,.,

# reduce 75 omitted

module_eval(<<'.,.,', 'dsl.y', 177)
  def _reduce_76(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 178)
  def _reduce_77(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 78 omitted

module_eval(<<'.,.,', 'dsl.y', 183)
  def _reduce_79(val, _values, result)
     result = {:from => val[1], :to => val[3]}
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Dsl
  end   # module Connect
