#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require 'connect/dsl'
  require 'connect/lexer'

module Connect
  class Dsl < Racc::Parser

module_eval(<<'...end dsl.y/module_eval...', 'dsl.y', 233)

  def parse(input)
    scan_str(input) unless empty_definition?(input)
  end

  def power(v1,v2)
    v1 ^ v2
  end

  def multiply(v1,v2)
    v1 * v2
  end

  def divide(v1,v2)
    v1 / v2
  end

  def add(v1,v2)
    v1 + v2
  end

  def subtract(v1,v2)
    v1 - v2
  end

  def do_or(v1,v2)
    v1 || v2
  end

  def do_and(v1,v2)
    v1 && v2
  end

  def on_error(token, value, vstack )
    position =  "Syntax error on line #{lineno} of config file '#{current_file}'"
    text = @ss.peek(20)
    unless value.nil?
      msg = "#{position} at value '#{value}' : #{text}"
    else
      msg = "#{position} at token '#{token}' : #{text}"
    end
    if @ss.eos?
      msg = "#{position}: Unexpected end of file"
    end
    raise ParseError, msg
  end
...end dsl.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    17,   134,     9,    10,   104,     9,    10,    24,    25,     9,
    10,   106,     9,    10,    36,    37,    39,    40,     9,    27,
   135,    36,    37,    11,    36,    37,    11,    24,    25,    14,
    11,    16,    14,    11,    16,   109,    14,    90,    16,    14,
    20,    16,     9,    10,    42,    43,   110,   111,    54,     9,
    27,    24,    25,    46,    47,    36,    37,     9,    10,    42,
    43,    24,    25,    54,    53,    76,    24,    25,    46,    47,
    94,     9,    10,    42,    43,     9,    27,    54,   112,    53,
    24,    25,    46,    47,    94,     9,    10,    42,    43,    36,
    37,    54,    92,    53,    24,    25,    46,    47,    87,     9,
    10,    42,    43,     9,    27,    54,   119,    53,    24,    25,
    46,    47,    39,    40,    97,    42,    43,    84,    20,    54,
    84,    53,    24,    25,    46,    47,    64,    63,    97,    42,
    43,   125,   126,    54,    60,    53,    24,    25,    46,    47,
    57,    33,    97,    42,    43,    32,    23,    54,    21,    53,
    24,    25,    46,    47,    20,   137,    97,    42,    43,   104,
    19,    54,   109,    53,    24,    25,    46,    47,   141,   142,
    97,    42,    43,   123,   nil,    54,   nil,    53,    24,    25,
    46,    47,   nil,   nil,    97,    42,    43,   nil,   nil,    54,
   nil,    53,    24,    25,    46,    47,   nil,   nil,    97,    42,
    43,   nil,   nil,    54,   nil,    53,    24,    25,    46,    47,
   nil,   nil,    97,    42,    43,   nil,   nil,    54,   nil,    53,
    24,    25,    46,    47,     9,    27,   nil,    80,    42,    43,
   nil,    39,    40,    53,    78,    24,    25,    46,    47,    80,
    42,    43,   nil,    80,    42,    43,   nil,    24,    25,    46,
    47,    24,    25,    46,    47,    42,    43,   nil,   nil,    42,
    43,   nil,    24,    25,    46,    47,    24,    25,    46,    47,
     9,    27,   nil,   nil,   nil,   nil,   nil,    39,    40,    65,
    66,    67,    68,    69,    70,    71 ]

racc_action_check = [
     1,   114,     1,     1,    72,     0,     0,    60,    60,    22,
    22,    75,    12,    12,    61,    61,    22,    22,    20,    20,
   114,    93,    93,     1,    95,    95,     0,    20,    20,     1,
    22,     1,     0,    12,     0,    77,    22,    61,    22,    12,
    80,    12,    53,    53,    53,    53,    82,    82,    53,    32,
    32,    53,    53,    53,    53,   112,   112,    23,    23,    23,
    23,    14,    14,    23,    53,    53,    23,    23,    23,    23,
    64,   110,   110,   110,   110,    15,    15,   110,    90,    23,
   110,   110,   110,   110,    63,   104,   104,   104,   104,    21,
    21,   104,    62,   110,   104,   104,   104,   104,    57,   111,
   111,   111,   111,    91,    91,   111,    94,   104,   111,   111,
   111,   111,   140,   140,   106,   106,   106,    56,    97,   106,
    55,   111,   106,   106,   106,   106,    35,    34,    70,    70,
    70,   107,   108,    70,    31,   106,    70,    70,    70,    70,
    26,    17,    69,    69,    69,    16,    13,    69,    11,    70,
    69,    69,    69,    69,    10,   119,    68,    68,    68,   124,
     9,    68,   136,    69,    68,    68,    68,    68,   137,   138,
    67,    67,    67,   105,   nil,    67,   nil,    68,    67,    67,
    67,    67,   nil,   nil,    66,    66,    66,   nil,   nil,    66,
   nil,    67,    66,    66,    66,    66,   nil,   nil,    71,    71,
    71,   nil,   nil,    71,   nil,    66,    71,    71,    71,    71,
   nil,   nil,    65,    65,    65,   nil,   nil,    65,   nil,    71,
    65,    65,    65,    65,   113,   113,   nil,    54,    54,    54,
   nil,   113,   113,    65,    54,    54,    54,    54,    54,   109,
   109,   109,   nil,   118,   118,   118,   nil,   109,   109,   109,
   109,   118,   118,   118,   118,   134,   134,   nil,   nil,    92,
    92,   nil,   134,   134,   134,   134,    92,    92,    92,    92,
    29,    29,   nil,   nil,   nil,   nil,   nil,    29,    29,    52,
    52,    52,    52,    52,    52,    52 ]

racc_action_pointer = [
     3,     0,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   157,
   121,   146,    10,   118,    50,    73,   113,   141,   nil,   nil,
    16,    82,     7,    55,   nil,   nil,   110,   nil,   nil,   268,
   nil,   106,    47,   nil,    93,    92,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   263,    40,   224,   114,   111,    96,   nil,   nil,
    -4,     7,    59,    52,    38,   209,   181,   167,   153,   139,
   125,   195,   -11,   nil,   nil,    -4,   nil,    20,   nil,   nil,
     7,   nil,    20,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    76,   101,   255,    14,   102,    17,   nil,    85,   nil,   nil,
   nil,   nil,   nil,   nil,    83,   148,   111,   106,   122,   236,
    69,    97,    48,   222,   -14,   nil,   nil,   nil,   240,   120,
   nil,   nil,   nil,   nil,   144,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   251,   nil,   147,   164,   144,   nil,
   103,   nil,   nil,   nil ]

racc_action_default = [
   -83,   -83,    -1,    -5,    -6,    -7,    -8,    -9,   -10,   -83,
   -18,   -83,   -83,   -83,   -83,   -83,   -83,   -83,    -2,   -17,
   -83,   -83,   -83,   -83,   -19,   -20,   -65,   -18,   -67,   -83,
   -75,   -83,   -83,   144,   -83,   -83,   -13,   -14,   -44,   -15,
   -16,   -45,    -3,    -4,   -21,   -22,   -23,   -24,   -25,   -26,
   -27,   -28,   -43,   -83,   -83,   -11,   -11,   -83,   -70,   -74,
   -83,   -83,   -73,   -81,   -81,   -83,   -83,   -83,   -83,   -83,
   -83,   -83,   -52,   -31,   -35,   -52,   -49,   -52,   -51,   -54,
   -56,   -57,   -83,   -62,   -12,   -63,   -64,   -66,   -76,   -68,
   -83,   -83,   -83,   -79,   -83,   -79,   -36,   -83,   -37,   -38,
   -39,   -40,   -41,   -42,   -53,   -83,   -53,   -83,   -83,   -53,
   -83,   -83,   -83,   -83,   -83,   -33,   -34,   -77,   -83,   -83,
   -78,   -29,   -30,   -46,   -52,   -48,   -50,   -55,   -58,   -60,
   -59,   -61,   -69,   -71,   -83,   -72,   -52,   -83,   -83,   -32,
   -83,   -82,   -47,   -80 ]

racc_goto_table = [
    41,     7,     7,    31,    38,    59,    52,    58,    35,    29,
    77,    56,    75,     7,    72,   115,   105,    31,    26,   107,
    62,   108,    81,     7,    34,    18,     1,   117,    55,   120,
    85,    86,    93,    95,    89,    61,   127,    28,    22,   114,
   nil,    74,   nil,   nil,    91,   nil,    18,   nil,    96,    98,
    99,   100,   101,   102,   103,    83,   nil,   139,   nil,   nil,
   116,   nil,   nil,   122,    88,   nil,   nil,   124,   138,   129,
   131,   nil,   nil,   nil,   136,   nil,   nil,    81,   nil,    31,
   140,   nil,   nil,   nil,   nil,   113,    81,   121,   nil,    59,
   nil,   133,    74,   128,   130,   132,   nil,   nil,    74,    74,
   nil,    31,   116,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    83,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   143,    83 ]

racc_goto_check = [
    12,     8,     8,    13,    11,    34,    16,    12,    13,    33,
    26,    13,    20,     8,    19,    22,    25,    13,    14,    25,
    13,    25,    15,     8,    14,     2,     1,    36,    23,    36,
    10,    10,    35,    35,    32,    31,    27,    30,     1,    21,
   nil,    13,   nil,   nil,    11,   nil,     2,   nil,    16,    16,
    16,    16,    16,    16,    16,     8,   nil,    22,   nil,   nil,
    15,   nil,   nil,    20,    14,   nil,   nil,    19,    25,    20,
    20,   nil,   nil,   nil,    26,   nil,   nil,    15,   nil,    13,
    25,   nil,   nil,   nil,   nil,    33,    15,    16,   nil,    34,
   nil,    12,    13,    16,    16,    11,   nil,   nil,    13,    13,
   nil,    13,    15,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     8,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    12,     8 ]

racc_goto_pointer = [
   nil,    26,    24,   nil,   nil,   nil,   nil,   nil,     1,   nil,
   -25,   -17,   -22,   -12,     4,   -32,   -17,   nil,   nil,   -39,
   -41,   -53,   -77,     5,   nil,   -56,   -44,   -73,   nil,   nil,
    22,     3,   -27,    -6,   -24,   -31,   -66 ]

racc_goto_default = [
   nil,   nil,     2,    45,     3,     4,     5,     6,    51,     8,
   nil,   118,   nil,    13,    44,    48,    73,    49,    50,   nil,
   nil,   nil,   nil,   nil,    12,   nil,   nil,    79,    82,    15,
   nil,   nil,   nil,   nil,    30,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 37, :_reduce_none,
  2, 37, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  0, 46, :_reduce_none,
  1, 46, :_reduce_none,
  1, 47, :_reduce_none,
  1, 47, :_reduce_none,
  1, 48, :_reduce_none,
  1, 48, :_reduce_none,
  2, 49, :_reduce_17,
  1, 49, :_reduce_18,
  1, 50, :_reduce_19,
  1, 50, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  3, 55, :_reduce_29,
  3, 55, :_reduce_30,
  1, 55, :_reduce_31,
  3, 57, :_reduce_32,
  1, 57, :_reduce_33,
  1, 58, :_reduce_none,
  1, 56, :_reduce_35,
  3, 59, :_reduce_36,
  3, 59, :_reduce_37,
  3, 59, :_reduce_38,
  3, 59, :_reduce_39,
  3, 59, :_reduce_40,
  3, 59, :_reduce_41,
  3, 59, :_reduce_42,
  1, 59, :_reduce_none,
  3, 60, :_reduce_44,
  3, 45, :_reduce_45,
  4, 53, :_reduce_46,
  6, 53, :_reduce_47,
  4, 53, :_reduce_48,
  2, 53, :_reduce_49,
  4, 54, :_reduce_50,
  2, 54, :_reduce_51,
  0, 61, :_reduce_none,
  1, 61, :_reduce_none,
  1, 62, :_reduce_none,
  3, 62, :_reduce_55,
  1, 64, :_reduce_56,
  1, 64, :_reduce_none,
  3, 63, :_reduce_58,
  3, 63, :_reduce_59,
  3, 63, :_reduce_60,
  3, 63, :_reduce_61,
  1, 63, :_reduce_62,
  4, 40, :_reduce_63,
  4, 41, :_reduce_64,
  2, 42, :_reduce_65,
  4, 42, :_reduce_66,
  2, 43, :_reduce_none,
  4, 43, :_reduce_none,
  6, 65, :_reduce_69,
  2, 66, :_reduce_70,
  3, 68, :_reduce_none,
  4, 67, :_reduce_72,
  1, 67, :_reduce_73,
  2, 69, :_reduce_none,
  1, 69, :_reduce_none,
  3, 70, :_reduce_76,
  6, 44, :_reduce_77,
  6, 44, :_reduce_78,
  0, 72, :_reduce_none,
  4, 72, :_reduce_80,
  0, 71, :_reduce_none,
  4, 71, :_reduce_82 ]

racc_reduce_n = 83

racc_shift_n = 144

racc_token_table = {
  false => 0,
  :error => 1,
  :SCOPE => 2,
  :IDENTIFIER => 3,
  :INTEGER => 4,
  :FLOAT => 5,
  :SELECTOR => 6,
  :DO => 7,
  "{" => 8,
  :END => 9,
  "}" => 10,
  :DOUBLE_QUOTED => 11,
  :SINGLE_QUOTED => 12,
  :BOOLEAN => 13,
  :UNDEF => 14,
  "," => 15,
  "^" => 16,
  "*" => 17,
  "/" => 18,
  "+" => 19,
  "-" => 20,
  :OR => 21,
  :AND => 22,
  :WITH => 23,
  "[" => 24,
  "]" => 25,
  ":" => 26,
  :HASH_ROCKET => 27,
  "=" => 28,
  :INCLUDE => 29,
  :INTO => 30,
  :IMPORT => 31,
  :FROM => 32,
  "(" => 33,
  ")" => 34,
  :TO => 35 }

racc_nt_base = 36

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SCOPE",
  "IDENTIFIER",
  "INTEGER",
  "FLOAT",
  "SELECTOR",
  "DO",
  "\"{\"",
  "END",
  "\"}\"",
  "DOUBLE_QUOTED",
  "SINGLE_QUOTED",
  "BOOLEAN",
  "UNDEF",
  "\",\"",
  "\"^\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "OR",
  "AND",
  "WITH",
  "\"[\"",
  "\"]\"",
  "\":\"",
  "HASH_ROCKET",
  "\"=\"",
  "INCLUDE",
  "INTO",
  "IMPORT",
  "FROM",
  "\"(\"",
  "\")\"",
  "TO",
  "$start",
  "dsl",
  "config",
  "number",
  "assignment",
  "connection",
  "include",
  "import",
  "definition",
  "with",
  "selector",
  "block_begin",
  "block_end",
  "literal",
  "string",
  "scalar",
  "value",
  "array",
  "hash",
  "values",
  "reference",
  "parameters",
  "parameter",
  "expression",
  "with_scope_do",
  "optional_comma",
  "hashpairs",
  "hashpair",
  "hashkey",
  "import_with_scope_begin",
  "import_with_scope_end",
  "datasource",
  "import_block",
  "import_statements",
  "import_statement",
  "iterator",
  "definition_block" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

module_eval(<<'.,.,', 'dsl.y', 47)
  def _reduce_17(val, _values, result)
     result = "#{val[0]}#{val[1]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 48)
  def _reduce_18(val, _values, result)
     result = "#{val[0]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 52)
  def _reduce_19(val, _values, result)
     result = interpolate(val[0])
    result
  end
.,.,

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'dsl.y', 71)
  def _reduce_29(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 72)
  def _reduce_30(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 73)
  def _reduce_31(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 77)
  def _reduce_32(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 78)
  def _reduce_33(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

# reduce 34 omitted

module_eval(<<'.,.,', 'dsl.y', 86)
  def _reduce_35(val, _values, result)
    result = reference(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 90)
  def _reduce_36(val, _values, result)
     result = power(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 91)
  def _reduce_37(val, _values, result)
     result = multiply(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 92)
  def _reduce_38(val, _values, result)
     result = divide(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 93)
  def _reduce_39(val, _values, result)
     result = add(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 94)
  def _reduce_40(val, _values, result)
     result = subtract(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 95)
  def _reduce_41(val, _values, result)
     result = do_or(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 96)
  def _reduce_42(val, _values, result)
     result = do_and(val[0],val[2])
    result
  end
.,.,

# reduce 43 omitted

module_eval(<<'.,.,', 'dsl.y', 104)
  def _reduce_44(val, _values, result)
     push_scope(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 108)
  def _reduce_45(val, _values, result)
     pop_scope 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 115)
  def _reduce_46(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 116)
  def _reduce_47(val, _values, result)
     result = val[3].unshift(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 117)
  def _reduce_48(val, _values, result)
     result = [val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 118)
  def _reduce_49(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 125)
  def _reduce_50(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 126)
  def _reduce_51(val, _values, result)
     result = MethodHash.new
    result
  end
.,.,

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

module_eval(<<'.,.,', 'dsl.y', 136)
  def _reduce_55(val, _values, result)
     result.merge!(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 140)
  def _reduce_56(val, _values, result)
     result = val[0].to_sym
    result
  end
.,.,

# reduce 57 omitted

module_eval(<<'.,.,', 'dsl.y', 145)
  def _reduce_58(val, _values, result)
     result = MethodHash[val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 146)
  def _reduce_59(val, _values, result)
     result = MethodHash[val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 147)
  def _reduce_60(val, _values, result)
     result = MethodHash[val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 148)
  def _reduce_61(val, _values, result)
     result = MethodHash[val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 149)
  def _reduce_62(val, _values, result)
     result = MethodHash[val[0].object_id, val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 156)
  def _reduce_63(val, _values, result)
     assign(val[0], val[2], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 160)
  def _reduce_64(val, _values, result)
     connect(val[0], val[2], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 167)
  def _reduce_65(val, _values, result)
     include_file(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 168)
  def _reduce_66(val, _values, result)
     include_file(val[1], val[3])
    result
  end
.,.,

# reduce 67 omitted

# reduce 68 omitted

module_eval(<<'.,.,', 'dsl.y', 180)
  def _reduce_69(val, _values, result)
     push_scope(val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 184)
  def _reduce_70(val, _values, result)
     pop_scope
    result
  end
.,.,

# reduce 71 omitted

module_eval(<<'.,.,', 'dsl.y', 191)
  def _reduce_72(val, _values, result)
     datasource( val[0], *val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 192)
  def _reduce_73(val, _values, result)
     datasource( val[0], *[])
    result
  end
.,.,

# reduce 74 omitted

# reduce 75 omitted

module_eval(<<'.,.,', 'dsl.y', 201)
  def _reduce_76(val, _values, result)
     import(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 209)
  def _reduce_77(val, _values, result)
     result = define(val[0], val[2], val[5], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'dsl.y', 211)
  def _reduce_78(val, _values, result)
     result = define(val[0], val[2], val[5], val[4])
    result
  end
.,.,

# reduce 79 omitted

module_eval(<<'.,.,', 'dsl.y', 217)
  def _reduce_80(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 81 omitted

module_eval(<<'.,.,', 'dsl.y', 222)
  def _reduce_82(val, _values, result)
     result = {:from => val[1], :to => val[3]}
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Dsl
  end   # module Connect
